### ISSUE TITLE
Chaining does't work with Typescript

### ISSUE THREAD

**Issue by lkurzyniec** [mattphillips/jest-chain#13]
It won't work for typescript.

- `package` version: ^1.1.2
- `node` version: 12.13.1
- `npm` version: 6.12.1

Steps to reproduce:
- clone `https://github.com/jsynowiec/node-typescript-boilerplate` repo
- `npm install`
- `npm install --save-dev jest-chain`
- add `setupFilesAfterEnv: ["jest-chain"]` to `jest.config.js`
- add `src\global.d.ts` file with `import 'jest-chain';`
- open `__tests__\main.spec.ts` file and modify to check is chaining works

![image](https://user-images.githubusercontent.com/5943484/69803547-c394af00-11dc-11ea-8e97-2137f7ea1f22.png)

**Comment by lkurzyniec** [comment]
In addition, it partially works with `jest-extended`, but break `IntelliSense` (completion list is empty)
![image](https://user-images.githubusercontent.com/5943484/69803811-6b11e180-11dd-11ea-95dd-67ba681b1a21.png)

**Comment by mattphillips** [comment]
Sorry for the delay in coming to this!

Should be fixed in: https://www.npmjs.com/package/jest-chain/v/1.1.3

Please re-open if you are still running into any issues
