### ISSUE TITLE
error TS2344: Type 'Matchers<Promise<ChainedMatchers<T>>, T>' does not satisfy the constraint 'Matchers<void, Matchers<ChainedMatchers<T>, T>>'.

### ISSUE THREAD

**Issue by d0whc3r** [mattphillips/jest-chain#28]
**Bug**

- `package` version: 1.1.5
- `node` version: 14.15.0
- `npm` (or `yarn`) version: 6.14.9

Relevant code or config

```javascript
error TS2344: Type 'Matchers<Promise<ChainedMatchers<T>>, T>' does not satisfy the constraint 'Matchers<void, Matchers<ChainedMatchers<T>, T>>'.
```

What you did:
I updated @types/jest from 26.0.15 to 26.0.18

What happened (please provide anything you think will help):
Types in @types/jest changed in 26.0.16 and are incompatible with jest-chain 1.1.5

Reproduction repository (if possible):

**Comment by mattphillips** [comment]
Hey @d0whc3r I'm not able to replicate this issue as of Jest@29. There is an example project [here](https://github.com/mattphillips/jest-chain/examples/typescript) with everything working.

Please feel free to re-open if the issue still exists
